data:extend({
    {
      type = "item",
      name = "dummy-item-red",
      icon = "__dummy-items-mod__/graphics/dummy-item-red.png",
      icon_size = 64,
      stack_size = 2048,
      subgroup = "circuit-network",
      order = "z[dummy-item-red]",
    },
    {
      type = "recipe",
      name = "dummy-item-red",
      enabled = true,
      ingredients = {},
      result = "dummy-item-red",
      energy_required = 0.01,
    },
    {
      type = "item",
      name = "dummy-item-green",
      icon = "__dummy-items-mod__/graphics/dummy-item-green.png",
      icon_size = 64,
      stack_size = 2048,
      subgroup = "circuit-network",
      order = "z[dummy-item-red]",
    },
    {
      type = "recipe",
      name = "dummy-item-green",
      enabled = true,
      ingredients = {},
      result = "dummy-item-green",
      energy_required = 0.01,
    },
    {
      type = "item",
      name = "dummy-item-yellow",
      icon = "__dummy-items-mod__/graphics/dummy-item-yellow.png",
      icon_size = 64,
      stack_size = 2048,
      subgroup = "circuit-network",
      order = "z[dummy-item-red]",
    },
    {
      type = "recipe",
      name = "dummy-item-yellow",
      enabled = true,
      ingredients = {},
      result = "dummy-item-yellow",
      energy_required = 0.01,
    },
    {
      type = "item",
      name = "dummy-item-blue",
      icon = "__dummy-items-mod__/graphics/dummy-item-blue.png",
      icon_size = 64,
      stack_size = 2048,
      subgroup = "circuit-network",
      order = "z[dummy-item-red]",
    },
    {
      type = "recipe",
      name = "dummy-item-blue",
      enabled = true,
      ingredients = {},
      result = "dummy-item-blue",
      energy_required = 0.01,
    },
})
